### ISSUE TITLE
aelf-playground save gas fee

### ISSUE THREAD

**Issue by AbigailDeng** [AElfProject/aelf-playground-next#42]
### Description
Add a button in the playground to notify users about saving gas fees. This could include a tooltip or a pop-up message explaining how to optimize their transactions.

### Tasks

- [x] Organize the requirements for saving gas fees, hold a meeting
- [x] Outline the frontend tasks
- [x] handover to Calla
